[colors]
draw_bold_text_with_bright_colors = false

[[colors.indexed_colors]]
color = "0x094655"
index = 17

[colors.bright]
black = "0x002b36"
blue = "0x839496"
cyan = "0x93a1a1"
green = "0x586e75"
magenta = "0x6c71c4"
red = "0xcb4b16"
white = "0xfdf6e3"
yellow = "0x657b83"

[colors.cursor]
cursor = "0x93a1a1"

[colors.normal]
black = "0x073642"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0xeee8d5"
yellow = "0xb58900"

[colors.primary]
background = "0x002b36"
foreground = "0x839496"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.normal]
family = "xos4 Terminus"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[window]
opacity = 1.0

[window.dimensions]
columns = 130
lines = 100
