#!/usr/bin/env bash

yay -Sy --needed \
    nvim \
    python-pynvim \
    nodejs \
    npm \
    yarn \
    ctags \
    python \
    python-pip \
    ipython \
    alacritty \
    cscope \
    ranger \
    ueberzug \
    atool \
    unrar \
    pwgen \
    gparted \
    ffmpeg \
    zathura \
    zathura-pdf-poppler \
    texlive \
    texlive-bin \
    ttf-font-awesome \
    terminus-font-italic \
    terminus-font-ll2-td1 \
    apache \
    yt-dlp \
    sxiv \
    xclip \
    imagemagick \
    pkgfile \
    thefuck \
    downgrade \
    myip \
    rsync \
    libreoffice-fresh-de \
    tlpui-git \
    keepassxc \
    wsdd \
    mpd \
    ncmpcpp \
    mpc \
    mpd-mpris \
    ums \
    parallel \
    ncdu \
    fzf \
    bfs-git \
    trash-cli \
 \
    cmake \
    ninja \
    clang \
    gdb \
    ccache \
    luacheck \
    luarocks \
    ccls \
    flake8 \
    python-pylint \
    python-rope \
    jedi-language-server \
    mypy \
    shellcheck \
    vint
